version: '3'
services:
  app:
    build:
      context: ./Go
    volumes:
      - "./Go:/go"
    container_name: simple-api-rbac
    ports:
      - "8080:8080"
    tty: true
    depends_on:
      - db
    links:
      - db
  db:
    build:
      context: ./MySQL
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: godb
      MYSQL_USER: docker
      MYSQL_PASSWORD: docker
    container_name: simple-api-rbac-db
    ports:
      - "3306:3306"
    tty: true